apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-claim
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeName: mysql-pv  # Référence directe à notre PV existant 