- name: Wait for all control-plane pods become created
  shell: "kubectl get po --namespace=ingress-nginx --selector=app.kubernetes.io/component=controller --output=jsonpath='{.items[*].metadata.name}'"
  register: nginx_controller_pod_created
  until: item in nginx_controller_pod_created.stdout
  retries: 10
  delay: 30
  with_items:
    - ingress-nginx-controller

- name: Wait for control-plane pods become ready
  shell: "kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=600s"
  register: nginx_controller_pod_ready
