adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: grafana.local
      paths:
        - path: /
          pathType: Prefix
  tls: []


persistence:
  enabled: false
