# - name: Wait for all control-plane pods become created
#   shell: "kubectl get po --namespace=kube-system --selector tier=control-plane --output=jsonpath='{.items[*].metadata.name}'"
#   register: control_plane_pods_created
#   until: item in control_plane_pods_created.stdout
#   retries: 10
#   delay: 30
#   with_items:
#     - etcd
#     - kube-apiserver
#     - kube-controller-manager
#     - kube-scheduler

# - name: Wait for control-plane pods become ready
#   shell: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s"
#   register: control_plane_pods_ready

- name: Wait for control-plane pods to be up
  shell: kubectl wait pod --all --for=condition=Ready --namespace=kube-system --timeout=600s
