name: Mirror Repository

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  mirror:
    name: Push content to mirror repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: 
            git@github.com:EpitechMscProPromo2025/T-CLO-902-NAN_4.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
